### ISSUE TITLE
Update to later DirectX/OpenGL and SVG support

### ISSUE THREAD

**Issue by z505** [astoeckel/andorra#1]
Hi, I realize you are not much interested right now in this project as you are busy with other things, but would it help you continue this project if there was money donated or you were paid something?

I'm interested in:
-it being updated to later versions of directx, as directx 9 is quite old which people no longer have installed on their system
-SVG display being added. SVG animation would be nice, and svg text display too.

I was thinking of adding a Bounty to Lazarus wiki to get someone working on it (or could try myself ;-)) but you in fact are the expert with this code.

Maybe you are even too busy, if someone paid you... and not so interested. If so just let me know.

Also, which OpenGL version is being used, by default?  (I should check).

Actually if opengl is almost as fast and just as useful as directx with only minor differences in speed or other minor differences, I guess directx support is not so important - but SVG would nice, and I don't know about opengl version being used...

**Comment by astoeckel** [comment]
Unfortunately I don't really have any time to work on Andorra, even if I was paid for it. As for your other questions:

* DirectX 9 should still be around for a long time. Applications always had to and still have to provide the DX9 redistributable the application was linked against. That being said, porting to another renderer is not really that much of an issue.
* SVG is a different beast entirely. Implementing a GPU SVG renderer will take at least a man-year worth of time.
* OpenGL version required is OpenGL 2. The only thing not supported I remember are high bitdepth render targets.
