### ISSUE TITLE
CPL (common public license) questions

### ISSUE THREAD

**Issue by z505** [astoeckel/andorra#3]
With the CPL, it seems a bit like the LGPL where you can ship a library with source code but your main application doesn't require being gpl/lgpl.  However I am confused a bit:

With lazarus/delphi you use unit files and they are directly linked into your exe, so if a person uses CPL licensed code in their exe, doesn't all their entire exe need to be CPL compatible (ship source of entire exe). In the case of freepascal they use a modified LGPL license and consider units libraries, even though technically units are not library, they are your program itself (linked in).

Did you intend the CPL being used with Andorra the same way as modified LGPL where you can pull in a CPL unit into your program and not ship sources with the main program? That's a bit different than what the pure lgpl requires which would not allow that: it must be a DLL, not a unit source file. But I'm not sure how the CPL works or what you intended - so clarification will be needed whether all the EXE must be shipped cpl, or whether just the cpl units pulled in to the uses clause must be CPL.

**Comment by astoeckel** [comment]
The way I interpreted the CPL when I started writing Andorra (beware, I was 14 years old back then), was that you can statically link the Andorra source code into your application. You only have to contribute changes to the Andorra source code back, but not license your entire application under the CPL.
